app/controllers/public/cart_items_controller.rb, app/views/public/cart_items/index.html.erb
会員画面_カート一覧機能 作成
会員画面_カート追加機能 作成
=> [add]cart_list

app/controllers/admin/passwords_controller.rb, app/controllers/admin/registrations_controller.rb, app/controllers/admin/sessions_controller.rb, app/controllers/public/passwords_controller.rb, app/controllers/public/registrations_controller.rb, app/controllers/public/sessions_controller.rb, app/views/layouts/admin/_header.html.erb, app/views/layouts/public/_header.html.erb, app/views/public/registrations/new.html.erb, app/views/public/sessions/new.html.erb
ヘッダーの「ようこそ」のところを変更
名前、住所などがデータベースにはいるようにしました
=> Customer sign in

app/controllers/public/cart_items_controller.rb, app/views/public/cart_items/index.html.erb, config/routes.rb
カートに「カートを空にする」を追加しました。
routes.rbに名前付きルートを追加する変更をしています。
=> [fix]cart_list

app/controllers/admin/customers_controller.rb, app/views/admin/customers/index.html.erb, app/views/admin/customers/show.html.erb
管理者側顧客一覧ページ追加、管理者側顧客詳細ページのコード修正。
=> [Add]views/admin/customer/show.html.erb

app/controllers/admin/customers_controller.rb, app/views/admin/customers/edit.html.erb
=> [Add] views/admin/customers/edit.html.erb

db/migrate/20200504044645_change_column_to_customer.rb, db/migrate/20200504073354_change_column_to_order.rb, db/migrate/20200504074015_change_column_to_order_item.rb, db/migrate/20200504090754_change_column_to_item.rb, db/migrate/20200504091026_change_column_to_genre.rb, db/schema.rb
schemaファイルの修正。 not nullとdefault値追加
=> [fix]db/schema.rb

app/controllers/admin/orders_controller.rb, app/views/admin/orders/index.html.erb
-m管理者側注文一覧ページ作成。　データが入ったら再度修正します。
=> [Add]views/admin/order/index.html.erb

app/controllers/public/shipping_addresses_controller.rb, app/models/shipping_address.rb, app/views/public/shipping_addresses/edit.html.erb, app/views/public/shipping_addresses/index.html.erb
会員画面_配送先一覧、編集機能のついかと直打ち禁止をしました。
レイアウトをきれいにするのはあとでやります
=> Shipping address

app/assets/stylesheets/admin.scss, app/assets/stylesheets/public.scss, app/views/layouts/admin/_header.html.erb
ヘッダーの検索画面の位置を修正しました。これであっているかは不安ですが
=> modify_header

app/controllers/public/items_controller.rb, app/views/public/items/index.html.erb, app/views/public/items/show.html.erb
=> Items index

app/controllers/admin/order_items_controller.rb, app/controllers/admin/orders_controller.rb, app/models/order.rb, app/models/order_item.rb, app/views/admin/orders/index.html.erb, app/views/admin/orders/show.html.erb, config/routes.rb
[Add]view/admin/orders/index.html.erb
=> [Add]view/admin/orders/index.html.erb

app/controllers/public/orders_controller.rb, app/models/order.rb, app/views/admin/orders/index.html.erb, app/views/public/orders/index.html.erb
=> order-index

app/assets/stylesheets/public.scss, app/controllers/admin/base.rb, app/controllers/admin/sessions_controller.rb, app/controllers/public/base.rb, app/controllers/public/customers_controller.rb, app/controllers/public/homes_controller.rb, app/controllers/public/items_controller.rb, app/controllers/public/orders_controller.rb, app/controllers/public/passwords_controller.rb, app/controllers/public/registrations_controller.rb, app/controllers/public/sessions_controller.rb, app/controllers/public/shipping_addresses_controller.rb, app/models/customer.rb, app/models/shipping_address.rb, app/views/layouts/admin/_header.html.erb, app/views/layouts/public.html.erb, app/views/layouts/public/_header.html.erb, app/views/public/customers/show.html.erb, app/views/public/passwords/edit.html.erb, app/views/public/shipping_addresses/edit.html.erb, app/views/public/shipping_addresses/index.html.erb
修正点
＃publicのログインしていないと見れない
＃customerとshipping_addressのvalidationとエラーメッセージ
＃ヘッダーにルートパスへのリンクを設置
＃パスワード変更をできるようにする
＃publicの直打ち禁止の記述
直打ち禁止やログイン制限は確認したつもりですが、漏れがあるかもしれません
=> modify header,validation

app/assets/stylesheets/public.scss, app/controllers/public/orders_controller.rb
デザイン修正のCSSの変更と、不具合No1 会員 カートカートの中身が空でも「情報入力に進む」が押せてしまうの修正を実装しました。
=> [fix]design_2

app/assets/stylesheets/public/customers.scss, app/assets/stylesheets/public/shipping_addresses.scss, app/controllers/public/customers_controller.rb, app/views/public/customers/edit.html.erb, app/views/public/customers/show.html.erb, app/views/public/customers/withdraw.html.erb, app/views/public/shipping_addresses/edit.html.erb, app/views/public/shipping_addresses/index.html.erb
publicのcustomerとshipping_addressのレイアウトを変更しました
=> fix_layout

app/controllers/public/cart_items_controller.rb, app/controllers/public/orders_controller.rb, app/views/public/orders/confirm.html.erb
不具合No.6.11.12.13.18の修正を実装しました。
=> [fix]cart_fix2

app/views/public/orders/new.html.erb
会員_注文情報入力画面のデザイン修正しました。
コンフリクト起きるので、CSSは後からプッシュします。
=> [fix]design_fix_4

app/assets/stylesheets/public/orders.scss, app/controllers/public/orders_controller.rb
=> [fix]design

app/assets/javascripts/public.js, app/views/layouts/public/_header.html.erb
=> [fix]design_fix_7

app/controllers/public/orders_controller.rb
=> Fix layout

app/assets/stylesheets/public/orders.scss, app/views/public/cart_items/index.html.erb
=> [fix]desigin_fix_8

app/views/public/orders/confirm.html.erb, app/views/public/orders/new.html.erb
=> [fix]design_fix_9

app/controllers/public/orders_controller.rb, app/models/shipping_address.rb
orders/create 配送先データから送付先を選択したとき、全てorder.address に登録されている不具合を修正しました
=> [fix]order

app/assets/stylesheets/public/orders.scss, app/views/public/orders/confirm.html.erb
=> [fix]design_fix_10

.gitignore, Gemfile, Gemfile.lock, app/assets/stylesheets/admin.scss, app/assets/stylesheets/public.scss, app/assets/stylesheets/public/homes.scss, app/views/public/items/index.html.erb, app/views/public/items/show.html.erb, config/cable.yml, config/database.yml, config/environments/production.rb, config/puma.rb
=> Deploy preparation
